name: Livestream Website to YouTube

on:
  schedule:
    # Chạy mỗi ngày lúc 18h15 giờ Việt Nam (tức 11h15 UTC)
    - cron: '15 11 * * *'
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub UI

jobs:
  livestream:
    runs-on: ubuntu-latest

    steps:
    - name: Cài Chromium, FFmpeg, Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser ffmpeg xvfb wmctrl x11-utils imagemagick

    - name: Khởi động màn hình ảo Xvfb
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 3

    - name: Mở trình duyệt trang soicau24h.club
      run: |
        export DISPLAY=:99
        chromium-browser \
          --no-sandbox \
          --disable-gpu \
          --disable-software-rasterizer \
          --window-size=1920,1080 \
          --start-fullscreen \
          --start-maximized \
          --kiosk "https://soicau24h.club" > /dev/null 2>&1 &
        sleep 20  # Chờ trang tải

    - name: Phát trực tiếp lên YouTube trong 10 phút
      run: |
        export DISPLAY=:99
        ffmpeg -f x11grab -video_size 1920x1080 -i :99 -r 30 \
          -vcodec libx264 -preset veryfast -pix_fmt yuv420p -g 50 \
          -b:v 3000k -maxrate 3000k -bufsize 6000k -f flv \
          -t 600 \
          "rtmp://a.rtmp.youtube.com/live2/avg2-ufgp-pf24-th2w-4ep9"
