name: Livestream Website to YouTube

on:
  schedule:
    # Chạy mỗi ngày lúc 18h15 giờ Việt Nam (tức 11h15 UTC)
    - cron: '15 11 * * *'
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub UI

jobs:
  livestream:
    runs-on: ubuntu-latest

    steps:
    - name: Cài đặt Chromium, FFmpeg và Xvfb
      run: |
        sudo apt update
        sudo apt install -y ffmpeg chromium-browser xvfb

    - name: Phát trực tiếp trang web lên YouTube
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &

        # Mở trình duyệt để tải trang
        chromium-browser --no-sandbox --disable-gpu --display=:99 --window-size=1920,1080 https://soicau24h.club &

        # Đợi trang web tải (có thể chỉnh nếu trang bạn tải lâu)
        sleep 15

        # Stream 10 phút (600 giây) lên YouTube
        ffmpeg -f x11grab -video_size 1920x1080 -i :99 -r 30 \
        -vcodec libx264 -preset veryfast -pix_fmt yuv420p -g 50 \
        -b:v 3000k -maxrate 3000k -bufsize 6000k -f flv \
        rtmp://a.rtmp.youtube.com/live2/avg2-ufgp-pf24-th2w-4ep9 -t 600
